import { Document, Page, Text, View, StyleSheet, Svg, Rect } from '@react-pdf/renderer'
import type { Candidate } from './screenings'

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: 'Helvetica', color: '#1a1f36' },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 2 },
  subtitle: { fontSize: 9, color: '#6b7280', marginBottom: 20 },
  scoreRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 18 },
  scoreValue: { fontSize: 32, fontWeight: 700 },
  scoreLabel: { fontSize: 9, color: '#6b7280', textTransform: 'uppercase' },
  verdictPill: { fontSize: 10, fontWeight: 700, paddingVertical: 4, paddingHorizontal: 10, borderRadius: 12 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginTop: 16, marginBottom: 6 },
  bodyText: { fontSize: 10, lineHeight: 1.5 },
  bullet: { fontSize: 10, lineHeight: 1.5, marginBottom: 3 },
  skillChip: { fontSize: 9, backgroundColor: '#eef2ff', color: '#3730a3', paddingVertical: 3, paddingHorizontal: 8, borderRadius: 10, marginRight: 6, marginBottom: 6 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap' },
  footer: { position: 'absolute', bottom: 24, left: 36, right: 36, fontSize: 8, color: '#9ca3af', textAlign: 'center' },
})

function verdictStyle(v: Candidate['verdict']) {
  if (v === 'Fit') return { backgroundColor: '#d1fae5', color: '#065f46' }
  if (v === 'Maybe') return { backgroundColor: '#fef3c7', color: '#92400e' }
  return { backgroundColor: '#f1f5f9', color: '#475569' }
}

export function CandidateFeedbackDocument({ candidate, jobTitle }: { candidate: Candidate; jobTitle?: string }) {
  const barWidth = 200
  const fillWidth = Math.max(0, Math.min(100, candidate.score)) / 100 * barWidth

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Candidate Feedback{jobTitle ? ` — ${jobTitle}` : ''}</Text>
        <Text style={styles.subtitle}>Prepared for {candidate.name ?? candidate.file_name ?? 'candidate'} · HireBest</Text>

        <View style={styles.scoreRow}>
          <View>
            <Text style={styles.scoreValue}>{candidate.score}</Text>
            <Text style={styles.scoreLabel}>Match score / 100</Text>
          </View>
          <Svg width={barWidth} height={10} viewBox={`0 0 ${barWidth} 10`}>
            <Rect x={0} y={0} width={barWidth} height={10} rx={5} fill="#e3e6f0" />
            <Rect x={0} y={0} width={fillWidth} height={10} rx={5} fill="#2f7bff" />
          </Svg>
          <Text style={[styles.verdictPill, verdictStyle(candidate.verdict)]}>{candidate.verdict}</Text>
        </View>

        <Text style={styles.sectionTitle}>Overall summary</Text>
        <Text style={styles.bodyText}>{candidate.summary || 'No summary available.'}</Text>

        <Text style={styles.sectionTitle}>Strengths</Text>
        {(candidate.strengths ?? []).length === 0 && <Text style={styles.bodyText}>No specific strengths recorded.</Text>}
        {(candidate.strengths ?? []).map((s, i) => <Text key={i} style={styles.bullet}>• {s}</Text>)}

        <Text style={styles.sectionTitle}>Areas for growth</Text>
        {(candidate.gaps ?? []).length === 0 && <Text style={styles.bodyText}>No specific gaps recorded.</Text>}
        {(candidate.gaps ?? []).map((g, i) => <Text key={i} style={styles.bullet}>• {g}</Text>)}

        <Text style={styles.sectionTitle}>Skills observed</Text>
        <View style={styles.chipRow}>
          {(candidate.skills ?? []).length === 0 && <Text style={styles.bodyText}>No skills recorded.</Text>}
          {(candidate.skills ?? []).map(s => <Text key={s} style={styles.skillChip}>{s}</Text>)}
        </View>

        <Text style={styles.footer}>This feedback was generated by HireBest's AI screening assistant to support your application experience.</Text>
      </Page>
    </Document>
  )
}
