export type Post = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  author: string
  body: string[]
}

export const posts: Post[] = [
  {
    slug: 'hirebest-vs-greenhouse-2026',
    title: 'HireBest vs Greenhouse (2026): Which is Right for Your Team?',
    excerpt: 'A direct comparison on pricing, AI features, and setup time — and which type of team belongs on each platform.',
    category: 'Comparison',
    date: 'Jun 4, 2026',
    readTime: '9 min read',
    author: 'HireBest Team',
    body: [
      "Greenhouse is the market leader in enterprise applicant tracking. It is also one of the most frequently Googled tools by people looking for an alternative to it. That is not a contradiction — it is a product-market fit story. Greenhouse was built for large, structured hiring programs at companies with dedicated talent operations teams. A lot of people buy it without being that company, and then go looking for something else.",
      "This comparison covers both tools honestly. Not to tell you Greenhouse is bad — it is genuinely excellent for the teams it was designed for. But to help you figure out whether you are that team before you sign an annual contract.",
      "## The pricing gap is real — and it compounds",
      "Greenhouse does not publish its prices. Every quote is custom, negotiated between your procurement team and a Greenhouse account executive. What procurement benchmarking data (Vendr, G2 reviewer comments, leaked quotes) consistently shows: Essential tier runs $5,500–$7,000 per year for a 50-person company with 3–5 active roles. Advanced tier — which adds sourcing automation, deeper reporting, and DEI dashboards — lands at $9,000–$15,000 per year. Enterprise (Expert) is custom-quoted and typically starts at $20,000.",
      "HireBest's pricing is public and flat. Basic is $400 per year — a standalone AI screener that runs locally, no cloud required. Advanced is $900 per year and adds multi-user access, custom branding, and bulk uploads of 50+ CVs. Custom Integrated is a $1,500 one-time payment for a full ATS with database storage, role-based dashboards, and API integration. No annual renewal on that last one — ever.",
      "The year-one gap between HireBest Advanced and Greenhouse Essential is approximately $6,100. That is not a rounding error. Over three years, before renewal escalators, it is $18,300.",
      "## What Greenhouse's per-seat model actually costs",
      "Greenhouse's pricing is not per-job. It is per-seat. Every recruiter, every hiring manager, and every interviewer who needs to access a candidate profile or leave a scorecard counts as a seat. The per-seat rate at Essential tier runs roughly $300–$500 per seat per year.",
      "A 50-person company with 2 dedicated recruiters might assume they need 2 seats. In practice, once you add 5 hiring managers and 10 interviewers who need to submit feedback, you are at 17 seats — and the math gets uncomfortable fast. The \"starting price\" conversation with a Greenhouse AE begins at 5 figures the moment you map your actual org chart to their seat model.",
      "HireBest's Advanced plan includes multi-user access at a single flat rate. Adding a fifth user, a tenth hiring manager, or a new recruiter costs nothing extra. The Custom Integrated tier adds role-based permissions (Admin, Recruiter, Viewer) for teams that need access controls — still no per-seat tax.",
      "## The renewal problem most people miss",
      "Greenhouse was acquired by Permira, a private equity firm. Standard multi-year contracts include annual escalators of 8–15% baked into the renewal terms. A team that negotiated a $6,000 deal in 2022 is renewing at $7,800–$9,000 today — without any change in their usage, headcount, or the features they use.",
      "This is the part that catches people off guard at renewal time. The year-one number is not the real cost. The real cost is year three after two compounding hikes applied to a number that was already larger than expected once seat counts were finalized.",
      "HireBest has no renewal escalators. The yearly plan renews at the same price. The one-time Custom Integrated tier has no renewal at all.",
      "## Feature by feature: what actually differs",
      "On AI scoring: HireBest scores each CV from 0 to 100 against the job description, with written reasoning that cites specific requirements met and gaps identified. Greenhouse has a basic ranking feature and keyword matching — useful, but not the same as per-candidate written analysis. If you need to understand *why* a candidate ranked where they ranked, HireBest's output is more actionable.",
      "On speed: HireBest screens 100 CVs in 38 seconds. This is a measured median across batches, not a marketing claim. Greenhouse does not have a bulk AI screening mode — candidates are reviewed individually through the pipeline.",
      "On setup time: HireBest takes 1–14 days from purchase to live, depending on the tier. Greenhouse implementations typically run 30–90 days, involving onboarding calls, integration configuration, and training sessions.",
      "On integrations: This is where Greenhouse wins decisively. It has 400+ marketplace integrations: Workday, BambooHR, DocuSign, LinkedIn Recruiter, background check vendors, video interview platforms, Zoom, and more. HireBest integrates with LinkedIn and Workday APIs. If your hiring workflow depends on a deep ecosystem of connected tools, Greenhouse's integration library is a genuine differentiator.",
      "On contract flexibility: HireBest has no annual contract requirement. Greenhouse's standard terms are annual with renewal escalators.",
      "## When Greenhouse is the right call",
      "Greenhouse earns its price tag in specific conditions. The clearest one: you have a dedicated talent operations function — meaning the talent team is 5+ people, including recruiters, coordinators, and sourcing specialists who need to collaborate inside one system simultaneously. At that scale, 400 integrations becomes a real productivity multiplier, not a spec-sheet item.",
      "Structured interview scorecards are the other real differentiator. If your hiring process requires panel interviews with quantitative rubrics, calibration sessions, and documented feedback trails for compliance or DEI reporting, Greenhouse's structured interview kit is purpose-built for that. It is a meaningfully better tool for that specific workflow.",
      "The company profile that belongs on Greenhouse: Series B+ tech company, 500+ employees, active compliance documentation requirements, hiring 100+ roles per year, talent team of 5 or more. If that describes your organization, Greenhouse's pricing is justified.",
      "## When HireBest is the smarter choice",
      "Most hiring teams are not enterprise talent functions. They are a founder screening 40 CVs on a Tuesday evening, a recruiter at a 50-person agency managing six client mandates simultaneously, or an HR lead at a 200-person company who needs to shortlist 120 applicants before a hiring manager review on Friday. For these workflows, a $7,000 annual contract with a 60-day implementation and per-seat pricing is not a solution. It is an obstacle.",
      "HireBest was built for the triage problem specifically. The most painful step in hiring for teams under 200 people is not candidate tracking — it is the 4 hours a recruiter spends reading the wrong resumes before they ever pick up the phone. HireBest compresses that to under a minute and returns a ranked shortlist with written reasoning for each candidate.",
      "The no-contract model also changes the risk calculation significantly. If you hire 30 roles this year and 5 next year, you are not locked into a 5-figure commitment that compounds annually. You pay $900, you use it, you renew or you do not.",
      "## The honest trade-off",
      "HireBest is a screening tool, not a full ATS. It does not do offer management, sourcing automation, structured interview scorecards, or the 400-integration ecosystem. If those are genuine requirements — not nice-to-haves, but actual blockers in your current workflow — Greenhouse is the right tool and its price reflects that.",
      "If your actual problem is a pile of CVs you need to triage fast, without a sales call, without a procurement cycle, and without paying per seat for every hiring manager who needs to see a shortlist — HireBest solves that problem and Greenhouse does not solve it better.",
      "The question is not which tool is better in the abstract. It is which problem you are actually paying to solve.",
    ],
  },
  {
    slug: 'ai-ats-wrong-way-to-think',
    title: "Why 'AI ATS' is the Wrong Way to Think About Hiring",
    excerpt: "The category label hides the real shift. AI doesn't replace your ATS — it replaces the part of your day spent reading the wrong resumes.",
    category: 'Opinion',
    date: 'Feb 15, 2026',
    readTime: '5 min read',
    author: 'HireBest Team',
    body: [
      "Everyone is calling their product an \"AI ATS\" now. The category label has become a sales pitch, and like most sales pitches, it obscures more than it explains.",
      "Here's what's actually going on — and why the framing matters more than you'd expect.",
      "## What an ATS does",
      "An Applicant Tracking System is, at its core, a database with a workflow on top. It stores candidate records, routes applications to the right people, tracks where each candidate is in the hiring process, and keeps records for compliance.",
      "Greenhouse, Workable, Lever — these are all doing versions of the same thing. The workflow varies. The integrations vary. The price varies considerably. But the underlying job is identical: keep track of who applied, where they are, and what happened.",
      "## What AI actually does in hiring",
      "When companies say \"AI ATS,\" they usually mean one of two things. The first is AI features added to an existing ATS — a ranking layer, a summary blurb, a smart filter. The second is a genuinely different product category: AI-first screening tools that don't replace your ATS but handle the job that ATS software was never designed for — actually evaluating whether a candidate is right for the role.",
      "> The ATS solved the storage and tracking problem. AI screening solves the evaluation problem. These are different problems, and conflating them leads to buying the wrong tool.",
      "## The question that cuts through it",
      "The question isn't \"is this AI?\" — everything is AI now, including the autocomplete on your phone. The question is: what specific step in the hiring process does this help with, and is that the step where I'm losing time?",
      "For most teams under 200 people, the painful step isn't candidate tracking. The painful step is the 4 hours a recruiter spends reading CVs before they ever pick up the phone. That's the evaluation problem. AI screening tools solve it.",
    ],
  },
  {
    slug: 'greenhouse-pricing-2026',
    title: "Greenhouse Pricing in 2026: What's Really Going On",
    excerpt: "Public benchmarks, leaked quotes, and procurement reports — what an annual Greenhouse contract actually costs SMEs in 2026.",
    category: 'Industry',
    date: 'Feb 8, 2026',
    readTime: '8 min read',
    author: 'HireBest Team',
    body: [
      "## The short version",
      "Greenhouse does not publish its prices. Every quote is custom, which means two companies hiring at the same volume can pay very different amounts. What procurement data, Vendr reports, and G2 reviewer comments consistently show is this: Essential tier starts around $5,000–$6,500 per year for teams under 100 employees. By the time you add hiring manager seats and interviewer access, that number often lands at $9,000–$14,000 in year one.",
      "## The three tiers Greenhouse actually sells",
      "Greenhouse sells Essential, Advanced, and Expert. Only Enterprise deals get Expert quotes. Most SMEs land on Essential or Advanced.",
      "**Essential** covers the core ATS: job postings, pipeline stages, scorecards, basic reporting. Real-world spend for a 50-person company with 3–5 active roles lands around $5,500–$7,000 per year.",
      "**Advanced** adds sourcing automations, deeper reporting, and DEI dashboards. Teams that need these features typically pay $9,000–$15,000 per year once seat counts go above 10.",
      "**Expert** is custom-quoted and designed for 500+ employee orgs running structured hiring programs at scale. Expect $20,000+ annually.",
      "## The per-seat problem",
      "Greenhouse's pricing model is not per-job — it is per-seat. Every recruiter, hiring manager, and interviewer who needs access counts as a seat. A 50-person company with 2 dedicated recruiters might think they need 2 seats. In practice, once you add 5 hiring managers and 10 interviewers who need to leave scorecards, you are looking at 17 seats.",
      "## The alternative math",
      "HireBest's Advanced plan costs $900 per year. It covers unlimited screening, multi-user access, bulk CV uploads, custom branding, and AI scoring with JD-cited reasoning. That is a $6,100 per year difference against Greenhouse Essential — before the renewal hikes kick in.",
    ],
  },
  {
    slug: 'screen-100-cvs-in-38-seconds',
    title: 'How to Screen 100 CVs in 38 Seconds',
    excerpt: 'A walkthrough of how AI scoring compresses a full afternoon of resume review into a single coffee break — without losing nuance.',
    category: 'Tutorials',
    date: 'Feb 1, 2026',
    readTime: '6 min read',
    author: 'HireBest Team',
    body: [
      "## Where the 38 seconds comes from",
      "38 seconds is the median time for a 100-CV batch on HireBest's scoring engine, measured across batches submitted in January and February 2026. The range is 28–54 seconds depending on file size and OCR complexity. 100 CVs in under a minute is not a marketing number — it is what the system logs show.",
      "## What actually happens in those 38 seconds",
      "When you drop 100 CVs and a job description into HireBest, three things run in parallel for each candidate: extraction, matching, and output generation.",
      "**Extraction.** The parser reads the raw file and pulls structured data: current title, company history, years of experience, education, skills listed.",
      "**Matching.** The scoring model reads the extracted candidate data against your job description, looking for explicit matches, implicit matches, and gaps.",
      "**Output generation.** For each candidate, the model writes a 0–100 fit score, a brief rationale, and 3–5 interview questions targeting the specific gaps.",
      "## The actual time saving",
      "If a hiring manager was previously spending 4 hours screening 50 CVs per role and hiring for 20 roles per year, that is 80 hours of resume reading annually. At a fully-loaded cost of $60/hour, that is $4,800 of management time on a task that takes the AI 8 minutes total. HireBest Advanced costs $900/year. The arithmetic is not complicated.",
    ],
  },
]

export const getPost = (slug: string) => posts.find(p => p.slug === slug)
