export type Post = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  author: string
  coverImage?: string
  body: string[]
}

export const posts: Post[] = [
  {
    slug: 'software-engineer-interview-questions',
    title: '50 Software Engineer Interview Questions (2026 Guide with What to Listen For)',
    excerpt: 'Free list of 50 software engineer interview questions — technical, behavioral, system design, situational. Includes what to listen for in each answer. Generate more with AI.',
    category: 'Hiring Guide',
    date: 'Jun 16, 2026',
    readTime: '12 min read',
    author: 'HireBest Team',
    coverImage: '/software-engineer-interview-questions-cover.png',
    body: [
      "Hiring a strong software engineer in 2026 isn't about finding someone who can solve LeetCode hards in 12 minutes. It's about finding someone who can ship working code, debug under pressure, communicate trade-offs to non-engineers, and not break the team culture. This guide gives you 50 questions across five categories, plus exactly what to listen for in each answer so you can spot the difference between a memorized response and real engineering judgment.",
      "Use these as your starting point. If you want questions tailored to your specific JD — Senior Backend on Go, Junior Frontend on React, Mid-level DevOps on AWS — [generate them in 30 seconds with HireBest's free Interview Question Generator](/tools/interview-questions).",
      "## How to use this guide",
      "Don't ask all 50. A good engineering interview loop is 5–7 well-chosen questions across the categories below, with strong follow-ups that probe whether the candidate actually understands what they're saying. Pick 1–2 technical fundamentals as warm-ups, 1–2 coding or problem-solving questions, 1 system design question for mid+ roles, 2–3 behavioral questions, and 1 culture or motivation question.",
      "For each answer, listen less for the \"right\" textbook response and more for how the candidate reasons through trade-offs, asks clarifying questions, and handles being wrong.",
      "## Technical fundamentals (questions 1–10)",
      "These are warm-ups. Strong candidates should answer them confidently and concisely. Weak ones either over-explain or memorize without understanding.",
      "**1. What's the difference between a process and a thread?** **Listen for:** memory sharing (threads share, processes don't), context switch cost, when they'd choose one over the other. A strong answer mentions concurrency model trade-offs.",
      "**2. Explain what happens when you type a URL into a browser.** **Listen for:** DNS resolution → TCP handshake → TLS → HTTP request → server → response → render. Bonus points for mentioning caching layers, CDNs, or DNS prefetching.",
      "**3. What's the difference between SQL and NoSQL?** **Listen for:** schema-on-write vs schema-on-read, consistency vs scalability, use cases. Red flag: \"NoSQL is faster.\" That's not the trade-off.",
      "**4. Explain Big O notation in plain English.** **Listen for:** growth rate as input size grows, not exact runtime. Strong candidates explain why O(log n) matters at scale and give a real example.",
      "**5. What is REST and how is it different from GraphQL?** **Listen for:** over-fetching/under-fetching, single endpoint vs multiple, when each is the right pick. Watch for candidates who name-drop without understanding.",
      "**6. What's the difference between authentication and authorization?** **Listen for:** \"who you are\" vs \"what you can do.\" Bonus: examples of OAuth, JWT, RBAC.",
      "**7. Explain how garbage collection works in your primary language.** **Listen for:** generational hypothesis, mark-and-sweep, when GC pauses matter (latency-sensitive systems). Specifics by language are fine.",
      "**8. What is a deadlock and how do you prevent it?** **Listen for:** the four conditions (mutual exclusion, hold and wait, no preemption, circular wait) and at least one prevention strategy.",
      "**9. What are the SOLID principles?** **Listen for:** not just naming them — listen for an example of when they applied (or violated) one. Memorized definitions don't count.",
      "**10. Explain idempotency.** **Listen for:** same operation, same result regardless of how many times it's called. Bonus: real example from API design or payments.",
      "## Coding and problem-solving (questions 11–20)",
      "These are the questions where you actually watch candidates think. The answer matters less than the process.",
      "**11. Reverse a linked list.** **Listen for:** clean iterative or recursive solution, edge cases (empty list, single node), and whether they can explain it without writing code first.",
      "**12. Find the first non-repeating character in a string.** **Listen for:** hash map approach (O(n)) vs nested loop (O(n²)). Strong candidates discuss the trade-off.",
      "**13. Given a sorted array, find two numbers that sum to a target.** **Listen for:** two-pointer approach. If they jump to brute force without considering the sorted hint, that's a small flag.",
      "**14. Detect a cycle in a linked list.** **Listen for:** Floyd's tortoise and hare. Memorized? Probably. But ask them to explain why it works.",
      "**15. Implement a basic LRU cache.** **Listen for:** hash map + doubly linked list. This is a classic, so it's less about novelty and more about clean implementation.",
      "**16. How would you find the kth largest element in an unsorted array?** **Listen for:** heap approach (O(n log k)) or quickselect (O(n) average). Sorting first works but loses points at scale.",
      "**17. Walk me through how you'd debug a production bug you can't reproduce locally.** **Listen for:** hypothesis-driven debugging, logs, observability tools, narrowing scope, willingness to bring in others.",
      "**18. You wrote code that passes all tests but a customer reports a bug. What now?** **Listen for:** reproducing the bug, writing a failing test first, then fixing. Watch for candidates who blame the customer.",
      "**19. How do you decide when to refactor vs rewrite?** **Listen for:** cost-benefit reasoning, test coverage as a prerequisite, awareness of risk. \"Rewrite everything\" is a red flag.",
      "**20. Explain a recent technical decision you made and what trade-offs you considered.** **Listen for:** specific context, named alternatives, why they picked what they picked. Vague answers mean the candidate didn't actually own the decision.",
      "## System design (questions 21–30)",
      "For mid-level and above. Strong candidates ask clarifying questions before drawing anything. Weak ones jump straight to a database.",
      "**21. Design a URL shortener like bit.ly.** **Listen for:** base62 encoding, hash strategy, database choice, scaling reads vs writes, caching layer.",
      "**22. Design a rate limiter.** **Listen for:** token bucket vs sliding window, where to enforce (gateway vs service), distributed coordination.",
      "**23. Design a notification system that sends 1M push notifications per hour.** **Listen for:** queue-based architecture, retries, idempotency, fanout patterns, monitoring.",
      "**24. How would you design Twitter's home timeline?** **Listen for:** fanout-on-write vs fanout-on-read, hybrid approach for celebrity accounts, caching trade-offs.",
      "**25. Walk me through how you'd design a chat application.** **Listen for:** websockets vs polling, message persistence, read receipts, scaling to millions of concurrent users.",
      "**26. How do you handle data consistency in a distributed system?** **Listen for:** CAP theorem awareness, eventual vs strong consistency, when they'd accept each. Avoid candidates who claim \"always strong consistency.\"",
      "**27. Design an autocomplete system.** **Listen for:** trie data structure, caching popular prefixes, real-time updates, personalization layer.",
      "**28. How would you scale a database that's hitting write limits?** **Listen for:** read replicas, sharding strategy, partitioning keys, when to introduce a queue.",
      "**29. Design a file storage service like Dropbox.** **Listen for:** chunking, deduplication, sync conflicts, offline support, metadata vs blob separation.",
      "**30. Walk me through your approach to a system design question you've never seen before.** **Listen for:** clarify requirements → estimate scale → high-level components → bottlenecks → iterate. The methodology is the answer.",
      "## Behavioral (questions 31–40)",
      "Use the STAR method (Situation, Task, Action, Result) as your listening framework. Vague answers are the biggest tell.",
      "**31. Tell me about a time you disagreed with a technical decision made by your team.** **Listen for:** data-driven persuasion, professional handling, willingness to disagree and commit. Red flag: villain stories where the candidate is always right.",
      "**32. Describe a situation where you had to work with a difficult colleague.** **Listen for:** empathy, conflict resolution, focus on shared goals. Watch for blame language.",
      "**33. Tell me about a time you shipped something that broke production.** **Listen for:** ownership, what they learned, what process changed afterward. Candidates who never broke prod either lied or didn't ship much.",
      "**34. Walk me through a project you're proud of.** **Listen for:** their specific contribution, real impact, what they'd do differently now.",
      "**35. Describe a time you had to learn a new technology quickly to ship a feature.** **Listen for:** learning approach, where they got stuck, how they validated they'd learned it correctly.",
      "**36. Tell me about a time you mentored a junior engineer.** **Listen for:** concrete examples, what the junior actually learned, patience under pressure. Senior+ role signal.",
      "**37. Describe a time you missed a deadline. What happened?** **Listen for:** root cause analysis, what they communicated and when, what they changed afterward.",
      "**38. Tell me about a time you received critical feedback.** **Listen for:** specific feedback, how they responded emotionally, what they actually changed. Defensive answers are a flag.",
      "**39. Walk me through a time you had to make a decision with incomplete information.** **Listen for:** trade-off reasoning, stakeholder communication, comfort with reversibility (\"if we're wrong, here's how we'd back out\").",
      "**40. Describe your biggest technical mistake. What did you learn?** **Listen for:** specificity, accountability, behavioral change after. \"No big mistakes\" means they're not telling you about them.",
      "## Culture, growth, and motivation (questions 41–50)",
      "These reveal whether the candidate actually wants this job, or whether they're shopping for the next offer.",
      "**41. Why do you want to work here specifically?** **Listen for:** specific knowledge of your product, team, or mission. Generic answers (\"you're growing fast and seem cool\") are a soft no.",
      "**42. What kind of engineering culture do you do your best work in?** **Listen for:** alignment with how your team actually works, not aspirational answers. Mismatch here costs you in month three.",
      "**43. Where do you want to be in three years?** **Listen for:** ambition that fits the role, not over- or under-shooting. A senior who wants to be CTO in 18 months isn't going to stay.",
      "**44. How do you stay current with the field?** **Listen for:** specific newsletters, communities, side projects, books. \"I read Hacker News\" is the bare minimum.",
      "**45. Tell me about a side project or open-source contribution.** **Listen for:** genuine curiosity, not portfolio padding. Optional but useful signal.",
      "**46. What's the hardest engineering problem you've worked on?** **Listen for:** technical depth, what made it hard, how they decomposed it. Watch for problems they didn't actually own.",
      "**47. How do you handle technical debt?** **Listen for:** incremental refactoring, paying it down inside feature work, when to escalate. \"Tech debt is bad\" is not an answer.",
      "**48. What questions do you have for us?** **Listen for:** thoughtful questions about team dynamics, the role, technical decisions. No questions is a strong negative.",
      "**49. What's a strong opinion you hold about software engineering that most engineers disagree with?** **Listen for:** actual conviction, reasoning, willingness to be wrong. Tests for independent thinking and intellectual honesty.",
      "**50. Why are you leaving your current role?** **Listen for:** honest reasons, no blame language, alignment with what your role actually offers. Repeated short tenures need a follow-up.",
      "## How to score a candidate across these questions",
      "A good rubric uses 1–4 ratings across five dimensions: **technical depth** (do they understand the fundamentals at the level the role needs?), **problem-solving** (can they break down ambiguous problems and reason about trade-offs?), **communication** (can they explain technical concepts to someone with less context?), **ownership** (do they take accountability for outcomes, or deflect to others?), and **culture fit** (will they thrive in how your team actually operates?).",
      "Calibrate with another interviewer after every loop. A candidate who scores 4/4 on technical but 2/4 on communication is a different hire than a 3/3 across the board — and the right call depends on what your team needs right now.",
      "## Speed up screening with HireBest",
      "Reading 100 CVs to find five candidates worth interviewing usually takes a full day. [HireBest does it in 38 seconds](/blog/screen-100-cvs-in-38-seconds) — every CV is scored against your JD with written reasoning, missing skills surfaced, and interview questions auto-generated for the candidates you want to talk to.",
      "No credit card. Bulk upload up to 200 CVs at once. [Try HireBest free](/signup) or see [transparent pricing from $400–$1,500/year](/pricing).",
      "## Frequently asked questions",
      "### How many questions should a software engineer interview include?",
      "Aim for 5–7 well-chosen questions per round, with strong follow-ups, across a 2–3 round loop. Trying to cover 15 questions in one round produces shallow signal on all of them. Depth over breadth.",
      "### Should I ask LeetCode-style coding questions in 2026?",
      "Only if the role actually requires that skill day-to-day. For most product engineering roles, system design and debugging questions predict on-the-job performance better than algorithmic puzzles. For competitive trading firms or core infra, hard coding rounds still make sense.",
      "### How do I tell if a candidate memorized their answer?",
      "Ask a follow-up that requires them to apply the concept somewhere new. Memorized candidates handle the canonical question well but stumble on adjacent variants. Real understanding survives the follow-up.",
      "### What's the best way to standardize interviews across multiple interviewers?",
      "Use a scorecard with 4–5 dimensions and a 1–4 scale, calibrate weekly, and have every interviewer write up notes within 24 hours. Inconsistent rubrics produce inconsistent hires.",
      "### Can AI generate interview questions tailored to a specific JD?",
      "Yes — [HireBest's Interview Question Generator](/tools/interview-questions) takes any job description and produces role-specific behavioral, technical, and situational questions in under a minute. Free to try.",
    ],
  },
  {
    slug: 'workable-pricing-2026',
    title: 'Workable Pricing in 2026: What You Actually Pay (Real Quotes + Hidden Costs)',
    excerpt: 'Published tiers, leaked add-on totals, and procurement reports — what a Workable annual contract actually costs SMEs in 2026.',
    category: 'Industry',
    date: 'Jun 15, 2026',
    readTime: '8 min read',
    author: 'HireBest Team',
    coverImage: '/workable-pricing-cover.png',
    body: [
      "## The short version",
      "Workable publishes its base prices, which is rare in the ATS world. The catch is that the base price isn't the price most teams pay. Starter opens at $149/month on annual billing, Standard at $299/month, and Premier at $599/month — but once you add Video Interviews, SMS Texting, and account for a few new hires bumping you into a higher headcount band, the real number for a 75-person company on Standard lands closer to $477/month. Annual contracts also default to a 5–8% renewal bump unless you negotiate a cap on day one.",
      "That puts most growing teams in the $5,800–$7,200 range for year one on Standard — about 8x what [HireBest Advanced](/pricing) charges for screening the same volume of CVs.",
      "## The four tiers Workable actually sells",
      "Workable sells Pay-as-you-go, Starter, Standard, and Premier publicly, with a custom-quoted Enterprise tier above 500 employees. The published prices look transparent. What gets buyers is the gap between the published price and the invoice.",
      "**Pay-as-you-go** is $99 per open role with no monthly commitment. It works for a solo founder hiring once or twice a year. Past four roles in a year the math falls apart and you should be on Starter.",
      "**Starter** runs $149/month on annual billing ($169 month-to-month), capped at 50 employees. You get two active job slots, basic application tracking, one-click posting to 200+ free boards, and native integrations with BambooHR, Rippling, ADP, and Gusto. What you don't get: AI sourcing, real reporting, Video Interviews, SMS Texting, Assessments, or the onboarding module. Most teams that pick Starter expecting it to last a year end up on Standard inside a quarter — the two-slot cap is the part that bites.",
      "**Standard** opens at $299/month on annual billing and is the tier Workable's sales team pushes hardest. You get unlimited job slots, AI sourcing across their 400M+ candidate database, structured interview kits, and team scorecards. What you don't get bundled: Video Interviews ($99–109/mo add-on), SMS Texting ($79–89/mo add-on), Assessments ($59/mo add-on), and Performance Reviews. Stack two of those on and you're at $477/month. Stack four and you're at $595/month — basically Premier money.",
      "**Premier** is $599/month on annual billing and bundles every premium tool by default. You also get unlimited custom reporting, real approval workflows, and a dedicated CSM. For mid-market teams that need three or more add-ons, Premier is the cheaper plan even though the sticker says otherwise.",
      "## The headcount problem",
      "Workable's pricing model isn't per-seat like [Greenhouse](/vs-greenhouse) or [Lever](/vs-lever). It's per-headcount. Every tier is priced against your total company employee count, not how many recruiters use the tool. A 50-person company with one recruiter and a 200-person company with one recruiter pay very different amounts for identical usage.",
      "For SMEs in growth mode, this creates budget unpredictability that's worth modelling before you sign. A team at 45 employees on Standard pays the base $299/month. The moment they hire to 51, they shift into the next headcount band and the bill climbs. The recruiter using the tool didn't change. The amount of recruiting work didn't change. The invoice did.",
      "The hidden cost most procurement teams miss: Workable typically opens renewal negotiations with a 5–8% increase. If you don't negotiate a price cap into the original contract, that compounds quietly. A $299/month Standard plan signed in 2026 lands closer to $336/month by 2028 even before you add a single new employee.",
      "## The add-on stack nobody walks you through",
      "The single biggest gap between Workable's brochure and Workable's invoice is the add-on stack. Video Interviews adds $99–109/month for one-way and live candidate interviews at scale. SMS Texting adds $79–89/month and drives 98% candidate response rates — about 60x faster than email. Assessments adds $59/month for skills tests on technical and operational roles. Performance Reviews — goal tracking and 360 feedback after hire — is quoted separately.",
      "A team using Video Interviews and SMS Texting (the most common combo for mid-market hiring) adds $178/month on top of Standard's $299. That's where the $477/month real-world cost comes from. Add Assessments on top and you're at $536/month — within $63 of Premier, which would have given you all three add-ons plus advanced reporting and a CSM for one flat price.",
      "The math gets uglier on multi-year contracts. Three years on Standard with Video + SMS at a 6% annual renewal hike looks like this: Year 1 is $3,588 base plus $2,256 in add-ons for a total of **$5,844**. Year 2 picks up a 6% renewal bump plus 10 new hires shifting you into the next headcount band — **$6,580**. Year 3 lands at roughly **$7,200** after another 6% bump and steady headcount creep. Three-year contract value: roughly **$19,624**. About triple what the homepage quoted you for year one.",
      "## The alternative math",
      "[HireBest Advanced](/pricing) costs $900 per year. It covers bulk CV screening with AI scoring and JD-cited reasoning, multi-user logins, custom company branding, screening history per JD, and the ability to upload 50+ PDFs at once. That's a $4,944 per year difference against a real-world Standard contract on Workable — before renewal hikes, before headcount creep, before you stack a third add-on.",
      "The honest framing: Workable and HireBest don't do exactly the same thing. Workable is a full ATS with pipelines, careers pages, and onboarding modules. HireBest is the screening layer — the part that takes a stack of 100 CVs and tells you which 10 to actually interview. Most SMEs we talk to don't need the full ATS suite. They need the screening to stop eating 8 hours a week. That's where the cost gap shows up.",
      "If you already have a lightweight HRIS or your team is small enough that pipelines live in a shared spreadsheet, [HireBest replaces the part of Workable that actually matters](/vs-workable) — the candidate-evaluation work — for a fraction of the cost. If you need the full ATS workflow, Workable Standard is a reasonable buy, but go in with eyes open on the add-on stack and the renewal cap.",
      "## Who Workable actually fits",
      "Workable is the right call if you're hiring 10+ roles a year, sit between 20 and 200 employees, want recruiting-grade features without Greenhouse-grade pricing, and your team already runs interviews through a structured pipeline. It's overkill for a founder hiring once a quarter, and it'll feel underpowered the moment you cross into venture-backed scale with 100+ open reqs and a dedicated recruiting team.",
      "Buy Workable if you're hiring across multiple departments at the same time, your recruiters need collaboration features like comments and structured scorecards, you want a branded careers page that doesn't look like 2014, and you're willing to negotiate a renewal cap before signing the annual contract.",
      "Look elsewhere if your bottleneck is candidate evaluation rather than pipeline management, you hire fewer than 5 roles a year (pay-per-job or a lean tool wins on cost), you need deep DEI reporting and approval chains ([Greenhouse](/vs-greenhouse) fits better), or your hiring volume is unpredictable and headcount-band jumps would blow your budget.",
      "Most SMEs we talk to fall into the \"candidate evaluation is the actual bottleneck\" camp. That's where [a lean AI screener](/pricing) saves more time and money than upgrading to Premier ever will.",
      "## How to negotiate Workable",
      "A few things buyers consistently leave on the table.",
      "**1. Price cap on renewal.** Workable's default 5–8% bump is negotiable. Ask for a 0% cap on the first renewal and 3% maximum thereafter. Most reps will agree if you push.",
      "**2. Add-on discounts.** Bundle Video Interviews and SMS Texting into the base contract instead of paying month-to-month rates. Workable will often discount the bundle by 15–20%.",
      "**3. Headcount band protection.** If you're growing fast, ask for a fixed price through a specific headcount range — for example, locked in up to 100 employees regardless of when you cross the next band.",
      "**4. Annual vs month-to-month math.** The 20% annual discount only makes sense if you're confident you'll still use the tool 12 months later. If you're early in your hiring cadence, the month-to-month premium is worth the flexibility.",
      "The buyers who do well on Workable don't pay the brochure price. They pay 15–25% under it because they asked.",
      "## Frequently asked questions",
      "### Does Workable offer a free trial?",
      "Yes. You get a 15-day free trial on Starter and Standard with no credit card up front. You can post one live job, collect applications, and test the integrations during that window. Premier and Enterprise both gate behind a demo and a custom quote.",
      "### Is Workable cheaper than Greenhouse?",
      "For small and mid-market teams, dramatically so. [Greenhouse Essential opens at $5,000–$6,500 per year](/blog/greenhouse-pricing-2026), and that's before per-seat fees push the year-one total to $9,000–$14,000. Workable Standard with realistic add-ons lands at $5,844 for year one — still pricier than [HireBest Advanced at $900/year](/pricing), but a fraction of Greenhouse.",
      "### Is Workable's pricing actually transparent?",
      "Mostly yes. Workable publishes base monthly prices for Starter, Standard, and Premier without forcing you through a sales gate. The fuzzy parts are exact headcount-tier breakpoints above 50 employees, Enterprise quotes, and renewal pricing. Add-on prices are published but rarely surfaced during demos.",
      "### What add-ons are included in the Premier plan?",
      "Premier bundles Video Interviews, SMS Texting, Assessments, and the advanced reporting suite at no extra cost. The crossover happens when a Standard buyer hits three add-ons. After that, Premier wins on per-month cost.",
      "### Can I cancel Workable mid-contract?",
      "Annual contracts lock you in for the full term and typically don't refund if you bail early. Month-to-month is cancellable anytime but costs about 20% more. The clean exit is to put a contract review on the calendar 60 days before renewal and renegotiate from there.",
    ],
  },
  {
    slug: 'hirebest-vs-greenhouse-2026',
    title: 'HireBest vs Greenhouse (2026): Which is Right for Your Team?',
    excerpt: 'A direct comparison on pricing, AI features, and setup time — and which type of team belongs on each platform.',
    category: 'Comparison',
    date: 'Jun 4, 2026',
    readTime: '9 min read',
    author: 'HireBest Team',
    body: [
      "Greenhouse is the market leader in enterprise applicant tracking. It is also one of the most frequently Googled tools by people looking for an alternative to it. That is not a contradiction — it is a product-market fit story. Greenhouse was built for large, structured hiring programs at companies with dedicated talent operations teams. A lot of people buy it without being that company, and then go looking for something else.",
      "This comparison covers both tools honestly. Not to tell you Greenhouse is bad — it is genuinely excellent for the teams it was designed for. But to help you figure out whether you are that team before you sign an annual contract.",
      "## The pricing gap is real — and it compounds",
      "Greenhouse does not publish its prices. Every quote is custom, negotiated between your procurement team and a Greenhouse account executive. What procurement benchmarking data (Vendr, G2 reviewer comments, leaked quotes) consistently shows: Essential tier runs $5,500–$7,000 per year for a 50-person company with 3–5 active roles. Advanced tier — which adds sourcing automation, deeper reporting, and DEI dashboards — lands at $9,000–$15,000 per year. Enterprise (Expert) is custom-quoted and typically starts at $20,000.",
      "[HireBest's pricing](/pricing) is public and simple. Starter is $49 per month for solo recruiters — 3 active jobs and 150 CVs per month. Growth is $99 per month (or $840 per year billed annually — a 29% saving) and adds multi-user access for 3 seats, bulk uploads, custom branding, and 500 CVs per month. Team is $199 per month for HR departments, with unlimited active jobs, 10 users, API access, and analytics. Every paid plan ships with a 14-day free trial. No credit card required.",
      "The year-one gap between HireBest Growth (billed annually at $840) and Greenhouse Essential is approximately $6,160. That is not a rounding error. Over three years, before renewal escalators, it is $18,480.",
      "## What Greenhouse's per-seat model actually costs",
      "Greenhouse's pricing is not per-job. It is per-seat. Every recruiter, every hiring manager, and every interviewer who needs to access a candidate profile or leave a scorecard counts as a seat. The per-seat rate at Essential tier runs roughly $300–$500 per seat per year.",
      "A 50-person company with 2 dedicated recruiters might assume they need 2 seats. In practice, once you add 5 hiring managers and 10 interviewers who need to submit feedback, you are at 17 seats — and the math gets uncomfortable fast. The \"starting price\" conversation with a Greenhouse AE begins at 5 figures the moment you map your actual org chart to their seat model.",
      "HireBest's Growth plan includes 3 users in the $99/month price, and Team plan covers 10 users in $199/month. Adding a fifth user on Growth costs nothing extra until you exceed the seat limit and upgrade tiers. The Team plan also adds role-based permissions (Admin, Recruiter, Viewer) for organisations that need access controls — still no per-seat tax.",
      "## The renewal problem most people miss",
      "Greenhouse was acquired by Permira, a private equity firm. Standard multi-year contracts include annual escalators of 8–15% baked into the renewal terms. A team that negotiated a $6,000 deal in 2022 is renewing at $7,800–$9,000 today — without any change in their usage, headcount, or the features they use.",
      "This is the part that catches people off guard at renewal time. The year-one number is not the real cost. The real cost is year three after two compounding hikes applied to a number that was already larger than expected once seat counts were finalized.",
      "HireBest has no renewal escalators. Your monthly price is the price you see on the pricing page today. Annual plans renew at the same locked rate.",
      "## Feature by feature: what actually differs",
      "On AI scoring: HireBest scores each CV from 0 to 100 against the job description, with written reasoning that cites specific requirements met and gaps identified. Greenhouse has a basic ranking feature and keyword matching — useful, but not the same as per-candidate written analysis. If you need to understand *why* a candidate ranked where they ranked, HireBest's output is more actionable.",
      "On speed: HireBest screens 100 CVs in 38 seconds. This is a measured median across batches, not a marketing claim. Greenhouse does not have a bulk AI screening mode — candidates are reviewed individually through the pipeline.",
      "On setup time: HireBest takes 1–14 days from purchase to live, depending on the tier. Greenhouse implementations typically run 30–90 days, involving onboarding calls, integration configuration, and training sessions.",
      "On integrations: This is where [Greenhouse](/vs-greenhouse) wins decisively. It has 400+ marketplace integrations: Workday, BambooHR, DocuSign, LinkedIn Recruiter, background check vendors, video interview platforms, Zoom, and more. HireBest integrates with LinkedIn and Workday APIs. If your hiring workflow depends on a deep ecosystem of connected tools, Greenhouse's integration library is a genuine differentiator.",
      "On contract flexibility: HireBest has no annual contract requirement. Greenhouse's standard terms are annual with renewal escalators.",
      "## When Greenhouse is the right call",
      "Greenhouse earns its price tag in specific conditions. The clearest one: you have a dedicated talent operations function — meaning the talent team is 5+ people, including recruiters, coordinators, and sourcing specialists who need to collaborate inside one system simultaneously. At that scale, 400 integrations becomes a real productivity multiplier, not a spec-sheet item.",
      "Structured interview scorecards are the other real differentiator. If your hiring process requires panel interviews with quantitative rubrics, calibration sessions, and documented feedback trails for compliance or DEI reporting, Greenhouse's structured interview kit is purpose-built for that. It is a meaningfully better tool for that specific workflow.",
      "The company profile that belongs on Greenhouse: Series B+ tech company, 500+ employees, active compliance documentation requirements, hiring 100+ roles per year, talent team of 5 or more. If that describes your organization, Greenhouse's pricing is justified.",
      "## When HireBest is the smarter choice",
      "Most hiring teams are not enterprise talent functions. They are a founder screening 40 CVs on a Tuesday evening, a recruiter at a 50-person agency managing six client mandates simultaneously, or an HR lead at a 200-person company who needs to shortlist 120 applicants before a hiring manager review on Friday. For these workflows, a $7,000 annual contract with a 60-day implementation and per-seat pricing is not a solution. It is an obstacle.",
      "HireBest was built for the triage problem specifically. The most painful step in hiring for teams under 200 people is not candidate tracking — it is the 4 hours a recruiter spends reading the wrong resumes before they ever pick up the phone. HireBest compresses that to under a minute and returns a ranked shortlist with written reasoning for each candidate.",
      "The no-contract model also changes the risk calculation significantly. If you hire 30 roles this year and 5 next year, you are not locked into a 5-figure commitment that compounds annually. You pay $99 per month (or $840 per year for the annual saving), you use it, and you cancel from your dashboard if you do not need it anymore.",
      "## The honest trade-off",
      "HireBest is a screening tool, not a full ATS. It does not do offer management, sourcing automation, structured interview scorecards, or the 400-integration ecosystem. If those are genuine requirements — not nice-to-haves, but actual blockers in your current workflow — Greenhouse is the right tool and its price reflects that.",
      "If your actual problem is a pile of CVs you need to triage fast, without a sales call, without a procurement cycle, and without paying per seat for every hiring manager who needs to see a shortlist — HireBest solves that problem and Greenhouse does not solve it better.",
      "The question is not which tool is better in the abstract. It is which problem you are actually paying to solve.",
    ],
  },
  {
    slug: 'ai-ats-wrong-way-to-think',
    title: "Why 'AI ATS' is the Wrong Way to Think About Hiring",
    excerpt: "The category label hides the real shift. AI doesn't replace your ATS — it replaces the part of your day spent reading the wrong resumes.",
    category: 'Opinion',
    date: 'Feb 15, 2026',
    readTime: '5 min read',
    author: 'HireBest Team',
    body: [
      "Everyone is calling their product an \"AI ATS\" now. The category label has become a sales pitch, and like most sales pitches, it obscures more than it explains.",
      "Here's what's actually going on — and why the framing matters more than you'd expect.",
      "## What an ATS does",
      "An Applicant Tracking System is, at its core, a database with a workflow on top. It stores candidate records, routes applications to the right people, tracks where each candidate is in the hiring process, and keeps records for compliance.",
      "[Greenhouse](/vs-greenhouse), [Workable](/vs-workable), [Lever](/vs-lever) — these are all doing versions of the same thing. The workflow varies. The integrations vary. The price varies considerably. But the underlying job is identical: keep track of who applied, where they are, and what happened.",
      "## What AI actually does in hiring",
      "When companies say \"AI ATS,\" they usually mean one of two things. The first is AI features added to an existing ATS — a ranking layer, a summary blurb, a smart filter. The second is a genuinely different product category: AI-first screening tools that don't replace your ATS but handle the job that ATS software was never designed for — actually evaluating whether a candidate is right for the role.",
      "> The ATS solved the storage and tracking problem. AI screening solves the evaluation problem. These are different problems, and conflating them leads to buying the wrong tool.",
      "## The question that cuts through it",
      "The question isn't \"is this AI?\" — everything is AI now, including the autocomplete on your phone. The question is: what specific step in the hiring process does this help with, and is that the step where I'm losing time?",
      "For most teams under 200 people, the painful step isn't candidate tracking. The painful step is the 4 hours a recruiter spends reading CVs before they ever pick up the phone. That's the evaluation problem. [AI screening tools](/pricing) solve it.",
    ],
  },
  {
    slug: 'greenhouse-pricing-2026',
    title: "Greenhouse Pricing in 2026: What's Really Going On",
    excerpt: "Public benchmarks, leaked quotes, and procurement reports — what an annual Greenhouse contract actually costs SMEs in 2026.",
    category: 'Industry',
    date: 'Feb 8, 2026',
    readTime: '8 min read',
    author: 'HireBest Team',
    body: [
      "## The short version",
      "Greenhouse does not publish its prices. Every quote is custom, which means two companies hiring at the same volume can pay very different amounts. What procurement data, Vendr reports, and G2 reviewer comments consistently show is this: Essential tier starts around $5,000–$6,500 per year for teams under 100 employees. By the time you add hiring manager seats and interviewer access, that number often lands at $9,000–$14,000 in year one.",
      "## The three tiers Greenhouse actually sells",
      "Greenhouse sells Essential, Advanced, and Expert. Only Enterprise deals get Expert quotes. Most SMEs land on Essential or Advanced.",
      "**Essential** covers the core ATS: job postings, pipeline stages, scorecards, basic reporting. Real-world spend for a 50-person company with 3–5 active roles lands around $5,500–$7,000 per year.",
      "**Advanced** adds sourcing automations, deeper reporting, and DEI dashboards. Teams that need these features typically pay $9,000–$15,000 per year once seat counts go above 10.",
      "**Expert** is custom-quoted and designed for 500+ employee orgs running structured hiring programs at scale. Expect $20,000+ annually.",
      "## The per-seat problem",
      "Greenhouse's pricing model is not per-job — it is per-seat. Every recruiter, hiring manager, and interviewer who needs access counts as a seat. A 50-person company with 2 dedicated recruiters might think they need 2 seats. In practice, once you add 5 hiring managers and 10 interviewers who need to leave scorecards, you are looking at 17 seats.",
      "## The alternative math",
      "[HireBest's Growth plan](/pricing) costs $99 per month — or $840 per year if you choose annual billing (a 29% saving). It covers 500 CVs per month across 10 active jobs with 3 users, bulk CV uploads, custom branding, and AI scoring with JD-cited reasoning. That is a $6,160 per year difference against [Greenhouse Essential](/vs-greenhouse) — before the renewal hikes kick in.",
    ],
  },
  {
    slug: 'screen-100-cvs-in-38-seconds',
    title: 'How to Screen 100 CVs in 38 Seconds',
    excerpt: 'A walkthrough of how AI scoring compresses a full afternoon of resume review into a single coffee break — without losing nuance.',
    category: 'Tutorials',
    date: 'Feb 1, 2026',
    readTime: '6 min read',
    author: 'HireBest Team',
    body: [
      "## Where the 38 seconds comes from",
      "38 seconds is the median time for a 100-CV batch on HireBest's scoring engine, measured across batches submitted in January and February 2026. The range is 28–54 seconds depending on file size and OCR complexity. 100 CVs in under a minute is not a marketing number — it is what the system logs show.",
      "## What actually happens in those 38 seconds",
      "When you drop 100 CVs and a job description into HireBest, three things run in parallel for each candidate: extraction, matching, and output generation.",
      "**Extraction.** The parser reads the raw file and pulls structured data: current title, company history, years of experience, education, skills listed.",
      "**Matching.** The scoring model reads the extracted candidate data against your job description, looking for explicit matches, implicit matches, and gaps.",
      "**Output generation.** For each candidate, the model writes a 0–100 fit score, a brief rationale, and 3–5 interview questions targeting the specific gaps.",
      "## The actual time saving",
      "If a hiring manager was previously spending 4 hours screening 50 CVs per role and hiring for 20 roles per year, that is 80 hours of resume reading annually. At a fully-loaded cost of $60/hour, that is $4,800 of management time on a task that takes the AI 8 minutes total. [HireBest Growth costs $99/month — $840 if you pay annually](/pricing). The arithmetic is not complicated.",
    ],
  },
]

export const getPost = (slug: string) => posts.find(p => p.slug === slug)
